name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudnn
  - cudatoolkit=11.2
  - cupy
  - dask
  - dask-ml
  - dask-labextension
  - datashader
  - featuretools
  - gh
  - git
  - grpcio=1.34
  - h5py=3.1
  - holoviews
  - hvplot
  - imbalanced-learn
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-nvdashboard
  - lightgbm
  - matplotlib
  - nccl
  - numba
  - numpy=1.19
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r file:requirements.txt
  - pyarrow
  - python=3.8
  - python-language-server
  - pyviz_comms
  - scikit-learn
  - scipy
  - shap
  - six=1.15
  - tensorboard
  - typing-extensions=3.7
  - umap-learn
  - wandb
  - xarray
  - xeus-python
  - xgboost
