name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - cudnn
  - cudatoolkit=11.2
  - cupy
  - dask
  - dask-ml
  - dask-labextension
  - datashader
  - featuretools
  - gh
  - git
  - h5py
  - holoviews
  - hvplot
  - imbalanced-learn
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-nvdashboard
  - lightgbm
  - matplotlib
  - nccl
  - numba
  - numpy
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python
  - python-language-server
  - pyviz_comms
  - scikit-learn
  - scipy
  - shap
  - tensorboard
  - tensorflow=2.6.2
  - umap-learn
  - wandb
  - xarray
  - xeus-python
  - xgboost
